root: true
env:
  browser: true
  es2020: true
extends:
  - airbnb
  - airbnb-typescript
  - airbnb/hooks
  - plugin:prettier/recommended
ignorePatterns:
  - dist
  - vite.config.ts
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project: ./tsconfig.json
plugins:
  - react
rules:
  no-console: warn
  react/react-in-jsx-scope: off
  '@typescript-eslint/no-unused-vars': warn
  'react/jsx-props-no-spreading': 'off'
  'react/require-default-props': 'off'
